version: '2'

services:
  mysql:
    build: mysql
    container_name: "taskager_db"
    restart: always
    ports:
       - "3306:3306"
  
  graphite:
    image: hopsoft/graphite-statsd
    container_name: "taskager_graphite"
    restart: always
    ports:
     - "5000:80"
     - "2003-2004:2003-2004"
     - "2023-2024:2023-2024"
     - "8125:8125/udp"
     - "8126:8126"

  grafana:
    image: grafana/grafana
    container_name: "taskager_grafana"
    restart: always
    ports:
        - "3000:3000"
    links:
        - graphite
    volumes:
        - grafana:/var/lib/grafana

    environment:
        - GF_SECURITY_ADMIN_PASSWORD=ola123 



volumes:
        grafana:
