ALTER TABLE Interacao ADD COLUMN UserID int(10);
ALTER TABLE Sessao ADD COLUMN UserID int(10);
ALTER TABLE Sessao ADD INDEX FKSessao520031 (UserID), ADD CONSTRAINT FKSessao520031 FOREIGN KEY (UserID) REFERENCES `User` (ID);
ALTER TABLE Interacao ADD INDEX FKInteracao929740 (UserID), ADD CONSTRAINT FKInteracao929740 FOREIGN KEY (UserID) REFERENCES `User` (ID);
